<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\YadgarCafe.Domain\YadgarCafe.Domain.csproj" />
    <ProjectReference Include="..\YadgarCafe.Common\YadgarCafe.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Mapster" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\" />
    <Folder Include="Features\Categories\" />
    <Folder Include="Features\Inventory\" />
    <Folder Include="Features\Dashboard\" />
    <Folder Include="Features\Orders\" />
    <Folder Include="Features\Products\" />
    <Folder Include="Features\Roles\" />
    <Folder Include="Features\Users\" />
    <Folder Include="Interfaces\" />
    <Folder Include="DTOs\" />
    <Folder Include="Behaviors\" />
    <Folder Include="Mappings\" />
    <Folder Include="Common\" />
    <Folder Include="Services\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
